### ISSUE TITLE
可能的改进建议?

### ISSUE THREAD

**Issue by sleepyHolo** [superpung/tju-expense#1]
首先是如果使用python脚本的话实际上使用起来不算特别方便, 是否考虑直接发布exe版本? 可以顺便弄个简单的gui.
其次就是可以考虑使用Selenium之类的测试工具, 这样可以避免用户保存cookie. 不过如果需要完全自动化需要想个办法干掉网站的验证码, 如果需要可以参考一下我antiPIGAI项目用的自动化部分.
作为不算建议的建议, 关于获取数据部分的实现, 你使用的应该是直接分析html吧, 不知道能不能优化一下? 当然我自己不懂网页部分, 不过如果使用自动化的话, Selenium获取元素也是挺方便的.
Thanks!

**Comment by TimeCapsule1219** [comment]
首先给作者点个赞，无意在微北洋上看到了这个有趣的项目。
有点小建议，目前看到版本是0.1.0，已经封装为exe，但是时间局限为了2024年，还希望作者能否完善，使其可以指定年份生成，以及指定时间范围，这样可以看到自己校园阶段的全部消费

**Comment by TimeCapsule1219** [comment]
首先给作者点个赞，无意在微北洋上看到了这个有趣的项目。
有点小建议，目前看到版本是0.1.0，已经封装为exe，但是时间局限为了2024年，还希望作者能否完善，使其可以指定年份生成，以及指定时间范围，这样可以看到自己校园阶段的全部消费。

**Comment by superpung** [comment]
> 首先是如果使用python脚本的话实际上使用起来不算特别方便, 是否考虑直接发布exe版本? 可以顺便弄个简单的gui. 其次就是可以考虑使用Selenium之类的测试工具, 这样可以避免用户保存cookie. 不过如果需要完全自动化需要想个办法干掉网站的验证码, 如果需要可以参考一下我antiPIGAI项目用的自动化部分. 作为不算建议的建议, 关于获取数据部分的实现, 你使用的应该是直接分析html吧, 不知道能不能优化一下? 当然我自己不懂网页部分, 不过如果使用自动化的话, Selenium获取元素也是挺方便的. Thanks!

感谢你的建议！

1. 目前已经发布了 exe 版本，欢迎使用！
2. 验证码很容易干掉，但本项目没有加入对应代码，有几点原因。第一，本项目默认大家只爬取个人数据，所以用户保存自己账号的 cookie 并不会很麻烦。第二，出于网站安全性的考虑（以及对弱密码的保护），相比用户输入账号密码，由于 cookie 有失效时间（且不是很短），输入 cookie 更加安全，也不用担心泄露问题。
3. 当前对网页内容的解析并未发现问题，因此暂不考虑使用 Selenium。如果你发现有 bug 也欢迎指出！

**Comment by superpung** [comment]
> 首先给作者点个赞，无意在微北洋上看到了这个有趣的项目。 有点小建议，目前看到版本是0.1.0，已经封装为exe，但是时间局限为了2024年，还希望作者能否完善，使其可以指定年份生成，以及指定时间范围，这样可以看到自己校园阶段的全部消费。

感谢你的建议！
其实可以单独再开一个 issue 的，不过没关系！

1. 目前版本是可以指定年份的，可以看一下 README 哦！
2. 对于指定时间范围，感觉不会太常用（?）如果时间范围过小或过大，可视化的效果都会变差。当然这部分后续可以根据不同时间范围再完善布局，如果你有更好的实现想法欢迎再交流！
